# Generated by Django 4.1.5 on 2023-02-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_name_category_marque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantité',
            new_name='quantite',
        ),
    ]
