# Generated by Django 4.1.5 on 2023-03-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_quantité_product_quantite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_produit',
            new_name='produit_image',
        ),
    ]
